/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author hp
 */
public class FrameHome extends javax.swing.JFrame {

    /**
     * Creates new form FrameHome
     */
    public FrameHome() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRating = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bPembayaran = new javax.swing.JButton();
        bPemesanan = new javax.swing.JButton();
        bHistory = new javax.swing.JButton();
        bSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bRating.setBackground(new java.awt.Color(217, 217, 217));
        bRating.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 14)); // NOI18N
        bRating.setForeground(new java.awt.Color(51, 51, 51));
        bRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Rating Icon (1).png"))); // NOI18N
        bRating.setText("Penilaian");
        bRating.setBorder(null);
        bRating.setBorderPainted(false);
        bRating.setContentAreaFilled(false);
        bRating.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRatingActionPerformed(evt);
            }
        });
        getContentPane().add(bRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 150, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("mendaftarkan email Anda.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kami mengurus perawatan sepatu dengan tingkat profesionalisme tinggi. Kami menggunakan teknik khusus dan peralatan serta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("bahan premium untuk melakukan perawatan. Dapatkan pembaruan terkini mengenai Perawatan Sepatu dan Barang dengan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        bPembayaran.setBackground(new java.awt.Color(217, 217, 217));
        bPembayaran.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 14)); // NOI18N
        bPembayaran.setForeground(new java.awt.Color(51, 51, 51));
        bPembayaran.setText("Keranjang");
        bPembayaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217)));
        bPembayaran.setContentAreaFilled(false);
        bPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(bPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, 40));

        bPemesanan.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 18)); // NOI18N
        bPemesanan.setForeground(new java.awt.Color(204, 204, 204));
        bPemesanan.setText("PEMESANAN");
        bPemesanan.setContentAreaFilled(false);
        bPemesanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPemesanan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bPemesanan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPemesananActionPerformed(evt);
            }
        });
        getContentPane().add(bPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 160, 180));

        bHistory.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 18)); // NOI18N
        bHistory.setForeground(new java.awt.Color(204, 204, 204));
        bHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/History_1.png"))); // NOI18N
        bHistory.setText("HISTORY");
        bHistory.setContentAreaFilled(false);
        bHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bHistory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(bHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 170, 190));

        bSignOut.setBackground(new java.awt.Color(102, 102, 102));
        bSignOut.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        bSignOut.setForeground(new java.awt.Color(255, 255, 255));
        bSignOut.setText("Sign Out");
        bSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(bSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Home1_1.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRatingActionPerformed
        // TODO add your handling code here:
        FramePenilaian fp = new FramePenilaian();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(FrameLogin.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_bRatingActionPerformed

    private void bPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPembayaranActionPerformed
        // TODO add your handling code here:
        FrameMetodePembayaranIsi pm = new FrameMetodePembayaranIsi();
            pm.setVisible(true);
            pm.pack();
            pm.setLocationRelativeTo(null);
            this.dispose();
            
    }//GEN-LAST:event_bPembayaranActionPerformed

    private void bPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPemesananActionPerformed
        // TODO add your handling code here:
        FramePemesanan ps = new FramePemesanan();
            ps.setVisible(true);
            ps.pack();
            ps.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_bPemesananActionPerformed

    private void bHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoryActionPerformed
        // TODO add your handling code here:
        FrameRiwayatIsi rs = new FrameRiwayatIsi();
                rs.setVisible(true);
                rs.pack();
                rs.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_bHistoryActionPerformed

    private void bSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignOutActionPerformed
        // TODO add your handling code here:
        FrameLogin lg = new FrameLogin();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_bSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHistory;
    private javax.swing.JButton bPembayaran;
    private javax.swing.JButton bPemesanan;
    private javax.swing.JButton bRating;
    private javax.swing.JButton bSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
